# Generated by Django 5.0.6 on 2024-05-10 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookborrow',
            name='bookID',
        ),
        migrations.RemoveField(
            model_name='bookborrow',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bookborrow',
            name='userUID',
        ),
        migrations.RemoveField(
            model_name='bookborrow',
            name='userdp',
        ),
        migrations.RemoveField(
            model_name='bookborrow',
            name='username',
        ),
        migrations.AddField(
            model_name='bookborrow',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bookslist'),
        ),
        migrations.AddField(
            model_name='bookborrow',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='useableUID',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='borrow_id',
            field=models.CharField(default='ABmtzZk4i9wdbXO', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='request_handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_handled_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
