# Generated by Django 5.0.6 on 2024-05-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_bookborrow_bookid_remove_bookborrow_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookborrow',
            name='late_fine',
        ),
        migrations.RemoveField(
            model_name='bookborrow',
            name='remaining_days',
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='borrow_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='borrowed_for',
            field=models.CharField(choices=[('1', '1'), ('5', '5'), ('7', '7'), ('10', '10'), ('15', '15'), ('20', '20'), ('30', '30')], default='5', max_length=2),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='isEmailSend',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='isReturned',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='requested_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='timeUp',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
