# Generated by Django 5.0.6 on 2024-05-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_bookborrow_late_fine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookborrow',
            name='borrow_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
