# Generated by Django 5.0.6 on 2024-05-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bookborrow_borrow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrow',
            name='late_fine_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookborrow',
            name='remaining_days_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
