# Generated by Django 5.0.6 on 2024-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bookborrow_accepted_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_code',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
