# Generated by Django 5.0.6 on 2024-05-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_session_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_pic_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
