# Generated by Django 5.0.6 on 2024-05-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customuser_custom_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_pic',
            new_name='default_profile_pic',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cover_pic_url',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='custom_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
