# Generated by Django 5.0.6 on 2024-05-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customuser_cover_pic_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrow',
            name='returned_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookborrow',
            name='taken_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pics/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cover_pic_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='default_profile_pic',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='profile_pics/'),
        ),
    ]
