# Generated by Django 5.0.6 on 2024-05-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_bookborrow_returned_time_bookborrow_taken_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='useableUID',
            new_name='staffID',
        ),
        migrations.RemoveField(
            model_name='bookborrow',
            name='remaining_days_count',
        ),
    ]
