# Generated by Django 5.0.6 on 2024-05-19 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_notificationgroup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationgroup',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
