# Generated by Django 5.0.6 on 2024-05-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_notification_notification_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Borrowed', 'Borrowed'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=100),
        ),
    ]
