# Generated by Django 5.0.6 on 2024-05-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_notification_subject_alter_bookborrow_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookslist',
            old_name='available',
            new_name='isAvailable',
        ),
        migrations.RenameField(
            model_name='bookslist',
            old_name='book_available',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='bookslist',
            old_name='name',
            new_name='title',
        ),
    ]
