# Generated by Django 5.0.6 on 2024-05-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_available_bookslist_isavailable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslist',
            name='label_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
