# Generated by Django 5.0.6 on 2024-05-21 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_bookslist_created_at_alter_bookslist_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookslist',
            name='isAvailable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
