# Generated by Django 5.0.6 on 2024-05-25 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_bookslist_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPopularBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.bookslist')),
            ],
        ),
    ]
