# Generated by Django 5.0.6 on 2024-05-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_mostpopularbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslist',
            name='label_url',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
